html validation fixes for 8406 (#48)
* Validation Fix: closed some trs, added a closing td and tr
error: Stray end tag "tr/td

* Validation Fix: added h1
info warning: Article lacks heading. Consider using "h2"-"h6" elements to add identifying headings to all articles.

* Validation Fix: escaped N
error: Element "n" not allowed as child of element "p" in this context.

* Validation Fix: added missing third column in the first row
info warning: A table row was 3 columns wide and exceeded the column count established by the first row (2)